### ISSUE TITLE
Reference `@nuxt/eslint-config` in the README

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt-modules/eslint#114]
Am I the only one finding configuring ESLint in Nuxt 3 very confusing ?
I'm trying to setup eslint for a JavaScript project (no Typescript), and I can't find reliable documentation.
Every `.eslintrc` file i find use `parser: '@typescript-eslint/parser'`, but I can't make it work with `@babel/eslint-parser`

- First, I used nuxi to create my project and renamed my `nuxt.config.ts` to `nuxt.config.js`.
- I also delete the `tsconfig.json` file.
- I created my `.eslintrc` with a basic config like this:

```
module.exports = {
    root: true,
    env: {
        browser: true,
        node: true,
    },
    parser: '@babel/eslint-parser',
    parserOptions: {
        ecmaVersion: 'latest',
        requireConfigFile: false,
        sourceType: 'module',
    },
    extends: [
        'eslint:recommended',
        'plugin:vue/essential',
        '@nuxt/eslint-config',
        'plugin:prettier/recommended',
        'prettier',
    ],
    plugins: ['prettier'],
};
```

But i get this error:
> Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". (1:0)
<img width="1275" alt="Screenshot 2023-10-08 at 10 23 43 PM" src="https://github.com/nuxt-modules/eslint/assets/17392251/9e83af34-4133-48fb-8e22-0c00a6fcb62d">

Second, shouldn't the nuxt 3 version of this module be in the `@nuxt` namespace instead of the `@nuxtjs` namespace ?
Because the `@nuxtjs/eslint-config` and `@nuxtjs/esling-config-typescript` package are meant for Nuxt 2 and the Nuxt 3 version are called `@nuxt/eslint-config` and `@nuxt/eslint-config-typescript`.

**Comment by XyoloJR** [comment]
It should be nice to reference that config `@nuxt/eslint-config` for sure.
I didn't find a running config before reading your post here.

Instead of babel parser you could try `vue-eslint-parser` from [eslint-plugin-vue](https://eslint.vuejs.org/user-guide/#how-to-use-a-custom-parser)

I manage to have a minimal config running for typescript with that `.eslinrc.json` : 
```json
{
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:vue/vue3-recommended",
        "@nuxt/eslint-config"
    ],
    "parser": "vue-eslint-parser",
    "parserOptions": {
        "parser": "@typescript-eslint/parser",
        "sourceType": "module"
    },
    "plugins": ["@typescript-eslint"],
    "root": true
}
```
