### ISSUE TITLE
ESLint Flat Config

### ISSUE THREAD

**Issue by GaborTorma** [nuxt-modules/eslint#115]
Please support [ESLint Flat Config](https://eslint.org/docs/latest/use/configure/configuration-files-new).

I received the following error message when I try to use ES6 `eslint.config.js:`
`Cannot start nuxt:  No ESLint configuration found in `

**Comment by GaborTorma** [comment]
Reproduction link: https://stackblitz.com/edit/nuxt-starter-41k9jt?file=eslint.config.js

**Comment by SymphonySimper** [comment]
+1

**Comment by yveeven** [comment]
+1

**Comment by sandro-git** [comment]
how do you handle this issue ? what's the best way to do it work ?

**Comment by ModyQyW** [comment]
Guys, please track https://github.com/nuxt-modules/eslint/pull/124.

If you are in a rush and can't wait to merge, use [patch-pacakge](https://github.com/ds300/patch-package) for npm and yarn v1, use [pnpm patch](https://pnpm.io/cli/patch) for pnpm, use [yarn patch](https://yarnpkg.com/cli/patch) for yarn v2 and above.

And please reconsider. You may not need to run eslint in build process. See https://github.com/ModyQyW/vite-plugin-eslint2#faq for more info.
