### ISSUE TITLE
ERROR [unhandledRejection] 

### ISSUE THREAD

**Issue by 42savage** [nuxt-modules/eslint#88]
Hi,
So today i wanted to learn nuxt3. I started with totally basic configurating. At first place I wanted to install eslint.
I installed it just like it is in the tutorial.
```
npm install -D eslint
```
and then
```
npm install -D @nuxtjs/eslint-module
```
and finally nuxt.config.ts
```
export default {
  modules: [
    // Simple usage
    '@nuxtjs/eslint-module',
  ]
}
```
This results with error

                                                                                                                                                             12:15:08  
Nuxi 3.3.2                                                                                                                                                   12:15:08  
Nuxt 3.3.2 with Nitro 2.3.2                                                                                                                                  12:15:08
                                                                                                                                                             12:15:11
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.0.102:3000/                                                                                                                     12:15:08  
  > Network:  http://192.168.238.1:3000/
  > Network:  http://192.168.64.1:3000/

 ERROR  Cannot start nuxt:  Cannot find module 'ajv/dist/compile/codegen'                                                                                    12:15:11
Require stack:
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\ajv-keywords\dist\definitions\typeof.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\ajv-keywords\dist\keywords\typeof.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\ajv-keywords\dist\keywords\index.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\ajv-keywords\dist\index.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\schema-utils\dist\validate.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\schema-utils\dist\index.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\eslint-webpack-plugin\dist\options.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\eslint-webpack-plugin\dist\index.js

  Require stack:
  - node_modules\ajv-keywords\dist\definitions\typeof.js
  - node_modules\ajv-keywords\dist\keywords\typeof.js
  - node_modules\ajv-keywords\dist\keywords\index.js
  - node_modules\ajv-keywords\dist\index.js
  - node_modules\schema-utils\dist\validate.js
  - node_modules\schema-utils\dist\index.js
  - node_modules\eslint-webpack-plugin\dist\options.js
  - node_modules\eslint-webpack-plugin\dist\index.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
  at Function.Module._load (internal/modules/cjs/loader.js:746:27)
  at Module.require (internal/modules/cjs/loader.js:974:19)
  at require (internal/modules/cjs/helpers.js:93:18)
  at Object.<anonymous> (node_modules\ajv-keywords\dist\definitions\typeof.js:3:19)
  at Module._compile (internal/modules/cjs/loader.js:1085:14)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  at Module.load (internal/modules/cjs/loader.js:950:32)
  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
  at Module.require (internal/modules/cjs/loader.js:974:19)

 ERROR  [unhandledRejection] Cannot find module 'ajv/dist/compile/codegen'                                                                                   12:15:11  
Require stack:
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\ajv-keywords\dist\definitions\typeof.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\ajv-keywords\dist\keywords\typeof.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\ajv-keywords\dist\keywords\index.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\ajv-keywords\dist\index.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\schema-utils\dist\validate.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\schema-utils\dist\index.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\eslint-webpack-plugin\dist\options.js
- C:\Users\Kamil\Desktop\Projekty\vue-mongo-tood-app\node_modules\eslint-webpack-plugin\dist\index.js

  Require stack:
  - node_modules\ajv-keywords\dist\definitions\typeof.js
  - node_modules\ajv-keywords\dist\keywords\typeof.js
  - node_modules\ajv-keywords\dist\keywords\index.js
  - node_modules\ajv-keywords\dist\index.js
  - node_modules\schema-utils\dist\validate.js
  - node_modules\schema-utils\dist\index.js
  - node_modules\eslint-webpack-plugin\dist\options.js
  - node_modules\eslint-webpack-plugin\dist\index.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
  at Function.Module._load (internal/modules/cjs/loader.js:746:27)
  at Module.require (internal/modules/cjs/loader.js:974:19)
  at require (internal/modules/cjs/helpers.js:93:18)
  at Object.<anonymous> (node_modules\ajv-keywords\dist\definitions\typeof.js:3:19)
  at Module._compile (internal/modules/cjs/loader.js:1085:14)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  at Module.load (internal/modules/cjs/loader.js:950:32)
  at Function.Module._load (internal/modules/cjs/loader.js:790:12)
  at Module.require (internal/modules/cjs/loader.js:974:19)

**Comment by craive** [comment]
I also had this problem.

`npm install --save-dev ajv`

This has temporarily solved it for me, but I would prefer a fix in this module without installing additional packages.

**Comment by 42savage** [comment]
I was trying to install ajv-keywords manually, but it didn't resolve my problem so i removed it.
Finally upgrading node version to 18 helped, but eslint now is asking for its configuration.
In nuxt2 it was provided by default, now it looks like I have to do it on my own. Is that right?

**Comment by ricardogobbosouza** [comment]
It was always necessary to configure eslint, both in nuxt 2 and in nuxt3
