### ISSUE TITLE
console.log output is clobbered when there are eslint warnings

### ISSUE THREAD

**Issue by ncphillips** [nuxt-modules/eslint#91]
[Discord Context](https://discord.com/channels/473401852243869706/1092867938635227268)

If I have the following component:
```vue
<template>
  <h1>Whaterver</h1>
</template>
<script setup>
if (process.server) {
  console.log('Server');
} else {
  console.log('Client');
}
</script>
```

By default 'no-console' is a warning. Because of that, I get eslint warnings in my console.

Printing those warnings clobbers my console.log so that I do not see the "Server" log output.

This isn't specific to "no-console", it's true for any kind of eslint warning.

**Comment by ricardogobbosouza** [comment]
Hi @ncphillips 
Could you provide a minimal reproduction?

**Comment by ncphillips** [comment]
I don't have one, sorry.

It's probably still an issue but I'm not working with Nuxt anymore
