### ISSUE TITLE
Can't use module with my nuxt 3 project getting error

### ISSUE THREAD

**Issue by sarwan920** [nuxt-modules/eslint#92]
Hello,

I have trying to use this eslint module my nuxt 3 project, but getting error mentioned in the screenshot.

I have eslint and @nuxtjs/eslint-module installed using npm, and added to the nuxt.config.ts file but still getting this error.

![image](https://user-images.githubusercontent.com/47607107/230521966-232f224d-72ec-4550-bf8c-42ceab9460e8.png)

**Comment by huynvebisolvn** [comment]
I had the same problem with nuxt 3.3.3
I hope it gets fixed soon

**Comment by ricardogobbosouza** [comment]
Hi @sarwan920, @huynvebisolvn 
Are you using `eslint-module` version 4?

**Comment by sebj54** [comment]
I had to create an eslint config file (like `.eslintrc`) to make it work.

**Comment by tanerijun** [comment]
To solve this issue, you need to create ESLint config file in your root. Here is an example:

File name: `.eslintrc`
```
{
  "root": true,
  "extends": ["@nuxtjs/eslint-config-typescript"],
  "rules": {
    "vue/multi-word-component-names": false
  }
}
```

**Comment by ricardogobbosouza** [comment]
It is necessary to create the eslint configuration file
https://eslint.org/docs/latest/use/configure/configuration-files

**Comment by whimsicaldreamer** [comment]
@ricardogobbosouza @tanerijun I am having a different error.

**.eslintrc**  

```
{
    "root": true,
    "extends": ["@nuxtjs/eslint-config-typescript"],
    "rules": {
      "vue/multi-word-component-names": false
    }
}
```

**package.json**  

![image](https://github.com/nuxt-modules/eslint/assets/8104493/f54ba4be-dd77-4981-8156-049c78219614)

**nuxt.config.ts**  

![image](https://github.com/nuxt-modules/eslint/assets/8104493/9e880dc7-824a-49be-a359-e94ad7fbe9c3)


### ERROR  

![image](https://github.com/nuxt-modules/eslint/assets/8104493/7cf16da0-3075-4bc7-ba07-9e285ee2ebb5)

**Comment by ricardogobbosouza** [comment]
Hi @whimsicaldreamer 

Have you tried reinstalling the dependencies?

```bash
rm -rf node_modules package-lock.json yarn.lock pnpm-lock.yaml 

npm install
# yarn install
# pnpm install
```

**Comment by whimsicaldreamer** [comment]
Yes @ricardogobbosouza, multiple times
