### ISSUE TITLE
integration problem with @nuxtjs/eslint-module

### ISSUE THREAD

**Issue by hosseinghs** [nuxt-modules/eslint#93]
Hi
I have a project created with nuxi, then I followed these steps to add eslint to my project: 
[](https://nuxt.com/modules/eslint)
after installing @nuxtjs/eslint-module I added the config to my nuxt.config.ts file as following: 
```
export default defineNuxtConfig({
   modules: [
     '@nuxtjs/eslint-module'
   ]
  })
```
PROBLEM is when I run yarn dev I get the error:
Cannot start nuxt:  Failed to import ESLint, do you install or configure eslintPath?

I install eslint version ^7 along side @nuxtjs/eslint-module and got the same error

**Comment by tanerijun** [comment]
You may need to create an ESLint config file in your project root. [example](https://github.com/nuxt-modules/eslint/issues/92#issuecomment-1545400284)
