### ISSUE TITLE
Module not in NPM

### ISSUE THREAD

**Issue by dondracek** [nuxt-modules/eslint#94]
I know this is not a code issue but we're getting a 404 from npm @nuxtjs/eslint-module in a nuxt2 project.
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nuxtjs%2feslint-module - Not found
npm ERR! 404
npm ERR! 404  '@nuxtjs/eslint-module@^4.0.2' is not in this registry.
did the package move/change name?

**Comment by Shanninchen** [comment]
Having the same issue with v2.0.0 :/

11:31:40 npm ERR! code E404
11:31:40 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nuxtjs/eslint-module/-/eslint-module-2.0.0.tgz
11:31:40 npm ERR! 404
11:31:40 npm ERR! 404 '@nuxtjs/eslint-module@2.0.0' is not in the npm registry.

**Comment by llllvvuu** [comment]
npm outage currently:

https://status.npmjs.org/incidents/drj38qn6qm59
https://github.com/search?q=+npm+ERR%21+404&type=issues&s=created&o=desc

**Comment by ricardogobbosouza** [comment]
For nuxt2 use https://github.com/nuxt-modules/eslint/tree/nuxt2
